### ISSUE TITLE
deploy fails on Linux

### ISSUE THREAD

**Issue by unwiredben** [rokudev/sublimetext-package#1]
https://github.com/rokudev/sublimetext-package/blob/master/plugin_source/RokuPlugin.py#L265 only will catch file names with backslashes (Windows form).  It needs to use all the https://docs.python.org/2/library/os.path.html methods to turn the filename path into parts instead of a regexp search in order to work on all OSes that support Sublime Text.

When I try on my Linux host, I get

```
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 797, in run_
    return self.run()
  File "RokuPlugin in /home/corp.roku/bcombee/.config/sublime-text-3/Installed Packages/RokuPlugin.sublime-package", line 71, in run
  File "RokuPlugin in /home/corp.roku/bcombee/.config/sublime-text-3/Installed Packages/RokuPlugin.sublime-package", line 287, in getArchivePath
PermissionError: [Errno 13] Permission denied: 'out'
```

**Comment by RokuRnD** [comment]
@unwiredben thanks for the PR, it will be reviewed. 

One question regarding `PermissionError: [Errno 13] Permission denied: 'out'`. Is this error still present? Cause it looks like you don't have proper permissions for dir/file creation from your user.

**Comment by unwiredben** [comment]
No, that's gone with my change.  The permission error was because the code didn't determine the right directory in which to try to make the out folder, so it ran in the current directory of the sublime text process.

**Comment by RokuRnD** [comment]
fixed in: https://github.com/rokudev/sublimetext-package/releases/tag/v.1.0.1
