### ISSUE TITLE
Code colouring isn't properly highlighting function names

### ISSUE THREAD

**Issue by sunmockyang-youi** [rokudev/sublimetext-package#6]
You can see in this example that the function name isn't highlighted in here. I'm using Sublime's default theme which is Monokai. Using Sublime 3.1.1 for osx, build 3176

![screen shot 2019-02-28 at 11 17 42 am](https://user-images.githubusercontent.com/10407467/53580885-8d8da600-3b4a-11e9-92f5-1d8f7d48002d.png)

**Comment by yurii-polishchuk** [comment]
Thank you for your request, but the sublime text package was decommissioned and is no longer maintained.
